[package]
name = "fibers_http_server"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
bytecodec = "0.2"
factory = "0.1"
fibers = "0.1"
fibers_tasque = "0.1"
futures = "0.1"
httpcodec = "0.1"
slog = "2"
trackable = "0.2"

[dev-dependencies]
sloggers = "0.2"
